server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri:  https://github.com/niteshtheqa/microservice-config
          clone-on-start: true
